# Starship Configuration
# https://starship.rs/config/

format = """
$username\
$hostname\
$directory\
$git_branch\
$time\
$line_break\
$character"""

[username]
style_user = "fg:#89b4fa"
style_root = "fg:#f38ba8"
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
style = "fg:#89b4fa"
format = '[@$hostname]($style) '
disabled = false

[directory]
style = "fg:#f9e2af"
format = "in [$path]($style) "
truncation_length = 5
truncation_symbol = "â€¦/"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "fg:#a6e3a1"
format = 'on [$symbol$branch]($style) '

[git_status]
style = "fg:#f38ba8"
format = '[$all_status$ahead_behind]($style) '

[time]
disabled = false
time_format = "%H:%M"
style = "fg:#cba6f7"
format = 'at [$time]($style) '

[character]
success_symbol = '[](bold fg:#a6e3a1)'
error_symbol = '[](bold fg:#f38ba8)'
vimcmd_symbol = '[](bold fg:#a6e3a1)'

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "fg:#fab387"
format = "took [$duration]($style)"

[line_break]
disabled = false

[status]
style = "fg:#f38ba8"
symbol = "ğŸ”´"
success_symbol = ""
not_executable_symbol = "ğŸš«"
not_found_symbol = "ğŸ”"
sigint_symbol = "ğŸ§±"
signal_symbol = "âš¡"
disabled = false
